---
- name: Using Variables # Name of the playbook
  hosts: internalservers # Specify the target of the hosts on which playbook will run, located at: /etc/ansible/hosts
  gather_facts: no # Specifies ansible should not gather facts about the target hosts

  vars: # Defines variables that can be used within the playbook
    web_server_port: 80
    app_version: "v1.0"


  tasks: # Begining of the list of the tasks that will be executed within the playbook
    - name: Print web server port # First task
      debug: # Debug module to display a message that includes the value of the web_server_port variable
        msg: "web server is running on port {{ web_server_port }}."

    - name: Print app version # Second task
      debug: # Debug module to display a message that includes the value of the app_version variable
        msg: "App version is {{ app_version }}."