---
- name: Configure web Server # Name of the playbook
  hosts: internalservers # Specify the target of the hosts on which playbook will run, located at: /etc/ansible/hosts
  become: yes # Run tasks as sudo

  tasks: # Begining of the list of the tasks that will be executed within the playbook
    - name: Update apt cache # First task
      apt: # apt module allows ansible to manage packages on ubuntu
        update_cache: yes # Parameter for apt module: specifies ansible should update the package cache on the target hosts

    - name: Stop nginx service # Second task
      service: # Modules for managing system services
        name: nginx # Parameter for service: specifies the name of the service to be managed which is "nginx"
        state: stopped # Parameter for service: specifies ansible should ensure the package is stopped (unistalled) on the target hosts

    - name: Uninstall nginx # Third task
      apt: # apt module allows ansible to manage packages on ubuntu
        name: nginx # Parameter for apt module: specifies the name of the package to be uninstalled which is "nginx"
        state: absent # Parameter for apt: specifies ansible should ensure "nginx" service is "absent" (stopped) state on the target hosts